"""
Django settings for DEPLOYMENT project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

"""
import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR=BASE_DIR /'templates'
TEMPLATES_DIR.mkdir(parents=True,exist_ok=True)
print(TEMPLATES_DIR)




# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', default='587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', default='True')
#EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', default='False') 
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', default=None)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', default=None)

DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'raulautomates@gmail.com')
SERVER_EMAIL = os.environ.get('EMAIL_HOST_USER', 'raulautomates@gmail.com')

# Email admins for sending emails
ADMINS = [('dominic','dominicomondi747@gamil.com')]
MANAGERS = ADMINS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =str(os.environ.get('DJANGO_SECRET_KEY',default=get_random_secret_key()))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG',default=False)
ALLOWED_HOSTS = [
    '.railway.app'
]
if DEBUG:
   ALLOWED_HOSTS+=[
        '127.0.0.1',
        'localhost'
    ]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#internal apps
     'TESTAPP',
     'Commando',

     
]

if DEBUG:
  INSTALLED_APPS.append(
    # ...
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    # ...
  )
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

     # ...Whitenoise middleware
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # ...
]

ROOT_URLCONF = 'DEPLOYMENT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DEPLOYMENT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL=str(os.environ.get('DATABASE_URL'))
if DATABASE_URL:
   import dj_database_url
   if DATABASE_URL.startswith('postgresql://postgres'):
    DATABASES={
        'default':dj_database_url.config(
            default=DATABASE_URL
        )
    }
  
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT=BASE_DIR /'static_root'

STATIC_ROOT.mkdir(exist_ok=True,parents=True)
STATIC_FILES_DIR=[
  BASE_DIR /'static_files'
]

#Whitenoise brotli file compression
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}